// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Item.Colon.Transcode.Universal.Decision;
using Kozshplxapi.Item.Colon.Transcode.Universal.Fallback;
using Kozshplxapi.Item.Colon.Transcode.Universal.Start;
using Kozshplxapi.Item.Colon.Transcode.Universal.Subtitles;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kozshplxapi.Item.Colon.Transcode.Universal
{
    /// <summary>
    /// Builds and executes requests for operations under \{transcodeType}\:\transcode\universal
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UniversalRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The decision property</summary>
        public global::Kozshplxapi.Item.Colon.Transcode.Universal.Decision.DecisionRequestBuilder Decision
        {
            get => new global::Kozshplxapi.Item.Colon.Transcode.Universal.Decision.DecisionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fallback property</summary>
        public global::Kozshplxapi.Item.Colon.Transcode.Universal.Fallback.FallbackRequestBuilder Fallback
        {
            get => new global::Kozshplxapi.Item.Colon.Transcode.Universal.Fallback.FallbackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The start property</summary>
        public global::Kozshplxapi.Item.Colon.Transcode.Universal.Start.StartRequestBuilder Start
        {
            get => new global::Kozshplxapi.Item.Colon.Transcode.Universal.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subtitles property</summary>
        public global::Kozshplxapi.Item.Colon.Transcode.Universal.Subtitles.SubtitlesRequestBuilder Subtitles
        {
            get => new global::Kozshplxapi.Item.Colon.Transcode.Universal.Subtitles.SubtitlesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Item.Colon.Transcode.Universal.UniversalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UniversalRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{transcodeType}/:/transcode/universal", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Item.Colon.Transcode.Universal.UniversalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UniversalRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{transcodeType}/:/transcode/universal", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
