// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kozshplxapi.Status.Sessions.Background
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BackgroundGetResponse_MediaContainer : global::Kozshplxapi.Models.MediaContainer, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The TranscodeJob property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kozshplxapi.Status.Sessions.Background.BackgroundGetResponse_MediaContainer_TranscodeJob>? TranscodeJob { get; set; }
#nullable restore
#else
        public List<global::Kozshplxapi.Status.Sessions.Background.BackgroundGetResponse_MediaContainer_TranscodeJob> TranscodeJob { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Status.Sessions.Background.BackgroundGetResponse_MediaContainer"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Kozshplxapi.Status.Sessions.Background.BackgroundGetResponse_MediaContainer CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kozshplxapi.Status.Sessions.Background.BackgroundGetResponse_MediaContainer();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "TranscodeJob", n => { TranscodeJob = n.GetCollectionOfObjectValues<global::Kozshplxapi.Status.Sessions.Background.BackgroundGetResponse_MediaContainer_TranscodeJob>(global::Kozshplxapi.Status.Sessions.Background.BackgroundGetResponse_MediaContainer_TranscodeJob.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::Kozshplxapi.Status.Sessions.Background.BackgroundGetResponse_MediaContainer_TranscodeJob>("TranscodeJob", TranscodeJob);
        }
    }
}
#pragma warning restore CS0618
