// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Media.Providers.Metadata.Group.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kozshplxapi.Media.Providers.Metadata.Group
{
    /// <summary>
    /// Builds and executes requests for operations under \media\providers\metadata\group
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GroupRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Kozshplxapi.media.providers.metadata.group.item collection</summary>
        /// <param name="position">The ID of the metadata agent provider group to get</param>
        /// <returns>A <see cref="global::Kozshplxapi.Media.Providers.Metadata.Group.Item.WithGroupItemRequestBuilder"/></returns>
        public global::Kozshplxapi.Media.Providers.Metadata.Group.Item.WithGroupItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("groupId", position);
                return new global::Kozshplxapi.Media.Providers.Metadata.Group.Item.WithGroupItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Media.Providers.Metadata.Group.GroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GroupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/providers/metadata/group?primaryIdentifier={primaryIdentifier}&title={title}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Media.Providers.Metadata.Group.GroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GroupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/providers/metadata/group?primaryIdentifier={primaryIdentifier}&title={title}", rawUrl)
        {
        }
        /// <summary>
        /// Get the list of all available metadata agent provider groups for this PMS.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Media.Providers.Metadata.Group.GroupGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kozshplxapi.Media.Providers.Metadata.Group.GroupGetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kozshplxapi.Media.Providers.Metadata.Group.GroupGetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kozshplxapi.Media.Providers.Metadata.Group.GroupGetResponse>(requestInfo, global::Kozshplxapi.Media.Providers.Metadata.Group.GroupGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This endpoint registers a new metadata agent provider group and creates a new MetadataAgentGroupItem for the primraryIdentifier.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Media.Providers.Metadata.Group.GroupPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kozshplxapi.Media.Providers.Metadata.Group.GroupPostResponse?> PostAsync(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.Group.GroupRequestBuilder.GroupRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kozshplxapi.Media.Providers.Metadata.Group.GroupPostResponse> PostAsync(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.Group.GroupRequestBuilder.GroupRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kozshplxapi.Media.Providers.Metadata.Group.GroupPostResponse>(requestInfo, global::Kozshplxapi.Media.Providers.Metadata.Group.GroupPostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the list of all available metadata agent provider groups for this PMS.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, "{+baseurl}/media/providers/metadata/group", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// This endpoint registers a new metadata agent provider group and creates a new MetadataAgentGroupItem for the primraryIdentifier.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.Group.GroupRequestBuilder.GroupRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.Group.GroupRequestBuilder.GroupRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Media.Providers.Metadata.Group.GroupRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kozshplxapi.Media.Providers.Metadata.Group.GroupRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kozshplxapi.Media.Providers.Metadata.Group.GroupRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// This endpoint registers a new metadata agent provider group and creates a new MetadataAgentGroupItem for the primraryIdentifier.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GroupRequestBuilderPostQueryParameters 
        {
            /// <summary>The identifier of the metadata agent provider which will be the primary for the group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("primaryIdentifier")]
            public string? PrimaryIdentifier { get; set; }
#nullable restore
#else
            [QueryParameter("primaryIdentifier")]
            public string PrimaryIdentifier { get; set; }
#endif
            /// <summary>The title of the metadata agent provider group to add.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("title")]
            public string? Title { get; set; }
#nullable restore
#else
            [QueryParameter("title")]
            public string Title { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
