// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Hubs.Metadata.Item.Postplay;
using Kozshplxapi.Hubs.Metadata.Item.Related;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kozshplxapi.Hubs.Metadata.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \hubs\metadata\{metadataId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithMetadataItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The postplay property</summary>
        public global::Kozshplxapi.Hubs.Metadata.Item.Postplay.PostplayRequestBuilder Postplay
        {
            get => new global::Kozshplxapi.Hubs.Metadata.Item.Postplay.PostplayRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The related property</summary>
        public global::Kozshplxapi.Hubs.Metadata.Item.Related.RelatedRequestBuilder Related
        {
            get => new global::Kozshplxapi.Hubs.Metadata.Item.Related.RelatedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Hubs.Metadata.Item.WithMetadataItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMetadataItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hubs/metadata/{metadataId}{?count*,onlyTransient*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Hubs.Metadata.Item.WithMetadataItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMetadataItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hubs/metadata/{metadataId}{?count*,onlyTransient*}", rawUrl)
        {
        }
        /// <summary>
        /// Get the hubs for a section by metadata item.  Currently only for music sections
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Hubs.Metadata.Item.WithMetadataGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kozshplxapi.Hubs.Metadata.Item.WithMetadataGetResponse?> GetAsync(Action<RequestConfiguration<global::Kozshplxapi.Hubs.Metadata.Item.WithMetadataItemRequestBuilder.WithMetadataItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kozshplxapi.Hubs.Metadata.Item.WithMetadataGetResponse> GetAsync(Action<RequestConfiguration<global::Kozshplxapi.Hubs.Metadata.Item.WithMetadataItemRequestBuilder.WithMetadataItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kozshplxapi.Hubs.Metadata.Item.WithMetadataGetResponse>(requestInfo, global::Kozshplxapi.Hubs.Metadata.Item.WithMetadataGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the hubs for a section by metadata item.  Currently only for music sections
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Hubs.Metadata.Item.WithMetadataItemRequestBuilder.WithMetadataItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Hubs.Metadata.Item.WithMetadataItemRequestBuilder.WithMetadataItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Hubs.Metadata.Item.WithMetadataItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kozshplxapi.Hubs.Metadata.Item.WithMetadataItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kozshplxapi.Hubs.Metadata.Item.WithMetadataItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get the hubs for a section by metadata item.  Currently only for music sections
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithMetadataItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Limit hub entries to count items</summary>
            [QueryParameter("count")]
            public int? Count { get; set; }
            /// <summary>Only return hubs which are &quot;transient&quot;, meaning those which are prone to changing after media playback or addition (e.g. On Deck, or Recently Added)</summary>
            [QueryParameter("onlyTransient")]
            public int? OnlyTransient { get; set; }
        }
    }
}
#pragma warning restore CS0618
