// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kozshplxapi.Status.Sessions
{
    /// <summary>The location of the client</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SessionsGetResponse_MediaContainer_Metadata_Session_location
    {
        [EnumMember(Value = "lan")]
        #pragma warning disable CS1591
        Lan,
        #pragma warning restore CS1591
        [EnumMember(Value = "wan")]
        #pragma warning disable CS1591
        Wan,
        #pragma warning restore CS1591
    }
}
