// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kozshplxapi.Status.Sessions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SessionsGetResponse_MediaContainer_Metadata : global::Kozshplxapi.Models.Metadata, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Info about the player being used</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_Player? Player { get; set; }
#nullable restore
#else
        public global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_Player Player { get; set; }
#endif
        /// <summary>Info about the playback session</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_Session? Session { get; set; }
#nullable restore
#else
        public global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_Session Session { get; set; }
#endif
        /// <summary>The user playing the content</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_User? User { get; set; }
#nullable restore
#else
        public global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_User User { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "Player", n => { Player = n.GetObjectValue<global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_Player>(global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_Player.CreateFromDiscriminatorValue); } },
                { "Session", n => { Session = n.GetObjectValue<global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_Session>(global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_Session.CreateFromDiscriminatorValue); } },
                { "User", n => { User = n.GetObjectValue<global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_User>(global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_User.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_Player>("Player", Player);
            writer.WriteObjectValue<global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_Session>("Session", Session);
            writer.WriteObjectValue<global::Kozshplxapi.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata_User>("User", User);
        }
    }
}
#pragma warning restore CS0618
