// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Updater.Apply;
using Kozshplxapi.Updater.Check;
using Kozshplxapi.Updater.Status;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kozshplxapi.Updater
{
    /// <summary>
    /// Builds and executes requests for operations under \updater
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdaterRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The apply property</summary>
        public global::Kozshplxapi.Updater.Apply.ApplyRequestBuilder Apply
        {
            get => new global::Kozshplxapi.Updater.Apply.ApplyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The check property</summary>
        public global::Kozshplxapi.Updater.Check.CheckRequestBuilder Check
        {
            get => new global::Kozshplxapi.Updater.Check.CheckRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Kozshplxapi.Updater.Status.StatusRequestBuilder Status
        {
            get => new global::Kozshplxapi.Updater.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Updater.UpdaterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpdaterRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/updater", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Updater.UpdaterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpdaterRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/updater", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
