// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Activities;
using Kozshplxapi.Butler;
using Kozshplxapi.Colon;
using Kozshplxapi.DownloadQueue;
using Kozshplxapi.Hubs;
using Kozshplxapi.Identity;
using Kozshplxapi.Item;
using Kozshplxapi.Library;
using Kozshplxapi.Livetv;
using Kozshplxapi.Log;
using Kozshplxapi.Media;
using Kozshplxapi.Photo;
using Kozshplxapi.PlayQueues;
using Kozshplxapi.Playlists;
using Kozshplxapi.Security;
using Kozshplxapi.Services;
using Kozshplxapi.Status;
using Kozshplxapi.Updater;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kozshplxapi
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiClient : BaseRequestBuilder
    {
        /// <summary>The activities property</summary>
        public global::Kozshplxapi.Activities.ActivitiesRequestBuilder Activities
        {
            get => new global::Kozshplxapi.Activities.ActivitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The butler property</summary>
        public global::Kozshplxapi.Butler.ButlerRequestBuilder Butler
        {
            get => new global::Kozshplxapi.Butler.ButlerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Colon property</summary>
        public global::Kozshplxapi.Colon.RequestBuilder Colon
        {
            get => new global::Kozshplxapi.Colon.RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The downloadQueue property</summary>
        public global::Kozshplxapi.DownloadQueue.DownloadQueueRequestBuilder DownloadQueue
        {
            get => new global::Kozshplxapi.DownloadQueue.DownloadQueueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hubs property</summary>
        public global::Kozshplxapi.Hubs.HubsRequestBuilder Hubs
        {
            get => new global::Kozshplxapi.Hubs.HubsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The identity property</summary>
        public global::Kozshplxapi.Identity.IdentityRequestBuilder Identity
        {
            get => new global::Kozshplxapi.Identity.IdentityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The library property</summary>
        public global::Kozshplxapi.Library.LibraryRequestBuilder Library
        {
            get => new global::Kozshplxapi.Library.LibraryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The livetv property</summary>
        public global::Kozshplxapi.Livetv.LivetvRequestBuilder Livetv
        {
            get => new global::Kozshplxapi.Livetv.LivetvRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The log property</summary>
        public global::Kozshplxapi.Log.LogRequestBuilder Log
        {
            get => new global::Kozshplxapi.Log.LogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The media property</summary>
        public global::Kozshplxapi.Media.MediaRequestBuilder Media
        {
            get => new global::Kozshplxapi.Media.MediaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The photo property</summary>
        public global::Kozshplxapi.Photo.PhotoRequestBuilder Photo
        {
            get => new global::Kozshplxapi.Photo.PhotoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The playlists property</summary>
        public global::Kozshplxapi.Playlists.PlaylistsRequestBuilder Playlists
        {
            get => new global::Kozshplxapi.Playlists.PlaylistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The playQueues property</summary>
        public global::Kozshplxapi.PlayQueues.PlayQueuesRequestBuilder PlayQueues
        {
            get => new global::Kozshplxapi.PlayQueues.PlayQueuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The security property</summary>
        public global::Kozshplxapi.Security.SecurityRequestBuilder Security
        {
            get => new global::Kozshplxapi.Security.SecurityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The services property</summary>
        public global::Kozshplxapi.Services.ServicesRequestBuilder Services
        {
            get => new global::Kozshplxapi.Services.ServicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Kozshplxapi.Status.StatusRequestBuilder Status
        {
            get => new global::Kozshplxapi.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updater property</summary>
        public global::Kozshplxapi.Updater.UpdaterRequestBuilder Updater
        {
            get => new global::Kozshplxapi.Updater.UpdaterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Kozshplxapi.item collection</summary>
        /// <param name="position">Type of transcode media</param>
        /// <returns>A <see cref="global::Kozshplxapi.Item.WithTranscodeTypeItemRequestBuilder"/></returns>
        public global::Kozshplxapi.Item.WithTranscodeTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("transcodeType", position);
                return new global::Kozshplxapi.Item.WithTranscodeTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.ApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://{IP-description}.{identifier}.plex.direct:{port}";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
        /// <summary>
        /// Information about this PMS setup and configuration
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kozshplxapi.GetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kozshplxapi.GetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kozshplxapi.GetResponse>(requestInfo, global::Kozshplxapi.GetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Information about this PMS setup and configuration
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
    }
}
#pragma warning restore CS0618
