// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kozshplxapi.Livetv.Dvrs.Item.Devices.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithDeviceDeleteResponse_MediaContainer_DVR : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Device property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kozshplxapi.Models.DeviceItems>? Device { get; set; }
#nullable restore
#else
        public List<global::Kozshplxapi.Models.DeviceItems> Device { get; set; }
#endif
        /// <summary>The key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The language property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>The lineup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lineup { get; set; }
#nullable restore
#else
        public string Lineup { get; set; }
#endif
        /// <summary>The uuid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uuid { get; set; }
#nullable restore
#else
        public string Uuid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Livetv.Dvrs.Item.Devices.Item.WithDeviceDeleteResponse_MediaContainer_DVR"/> and sets the default values.
        /// </summary>
        public WithDeviceDeleteResponse_MediaContainer_DVR()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Livetv.Dvrs.Item.Devices.Item.WithDeviceDeleteResponse_MediaContainer_DVR"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kozshplxapi.Livetv.Dvrs.Item.Devices.Item.WithDeviceDeleteResponse_MediaContainer_DVR CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kozshplxapi.Livetv.Dvrs.Item.Devices.Item.WithDeviceDeleteResponse_MediaContainer_DVR();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Device", n => { Device = n.GetCollectionOfObjectValues<global::Kozshplxapi.Models.DeviceItems>(global::Kozshplxapi.Models.DeviceItems.CreateFromDiscriminatorValue)?.AsList(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "language", n => { Language = n.GetStringValue(); } },
                { "lineup", n => { Lineup = n.GetStringValue(); } },
                { "uuid", n => { Uuid = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Kozshplxapi.Models.DeviceItems>("Device", Device);
            writer.WriteStringValue("key", Key);
            writer.WriteStringValue("language", Language);
            writer.WriteStringValue("lineup", Lineup);
            writer.WriteStringValue("uuid", Uuid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
