// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \media\providers\metadata\group\{groupId}\items\{providerId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProviderItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProviderItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/providers/metadata/group/{groupId}/items/{providerId}{?after*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProviderItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/providers/metadata/group/{groupId}/items/{providerId}{?after*}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes a metadata agent provider group item with the given id.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Modify a metadata agent provider group&apos;s items. This will assign the specified provider id to the group if it does not already exist.Providing the optional after query parameter on an existing group item will move its position in the group relative to the item with the specified ID.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderPutResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderPutResponse?> PutAsync(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderItemRequestBuilder.WithProviderItemRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderPutResponse> PutAsync(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderItemRequestBuilder.WithProviderItemRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPutRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderPutResponse>(requestInfo, global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderPutResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes a metadata agent provider group item with the given id.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/html");
            return requestInfo;
        }
        /// <summary>
        /// Modify a metadata agent provider group&apos;s items. This will assign the specified provider id to the group if it does not already exist.Providing the optional after query parameter on an existing group item will move its position in the group relative to the item with the specified ID.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderItemRequestBuilder.WithProviderItemRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderItemRequestBuilder.WithProviderItemRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Modify a metadata agent provider group&apos;s items. This will assign the specified provider id to the group if it does not already exist.Providing the optional after query parameter on an existing group item will move its position in the group relative to the item with the specified ID.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithProviderItemRequestBuilderPutQueryParameters 
        {
            /// <summary>The ID of the group item to place this item after. This only works if the group item already exists. A -1 value will place the item at the beginning.</summary>
            [QueryParameter("after")]
            public double? After { get; set; }
        }
    }
}
#pragma warning restore CS0618
