// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Livetv.Dvrs;
using Kozshplxapi.Livetv.Epg;
using Kozshplxapi.Livetv.Sessions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kozshplxapi.Livetv
{
    /// <summary>
    /// Builds and executes requests for operations under \livetv
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LivetvRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The dvrs property</summary>
        public global::Kozshplxapi.Livetv.Dvrs.DvrsRequestBuilder Dvrs
        {
            get => new global::Kozshplxapi.Livetv.Dvrs.DvrsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The epg property</summary>
        public global::Kozshplxapi.Livetv.Epg.EpgRequestBuilder Epg
        {
            get => new global::Kozshplxapi.Livetv.Epg.EpgRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sessions property</summary>
        public global::Kozshplxapi.Livetv.Sessions.SessionsRequestBuilder Sessions
        {
            get => new global::Kozshplxapi.Livetv.Sessions.SessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Livetv.LivetvRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LivetvRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/livetv", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Livetv.LivetvRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LivetvRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/livetv", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
