// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Hubs.Sections.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kozshplxapi.Hubs.Sections
{
    /// <summary>
    /// Builds and executes requests for operations under \hubs\sections
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SectionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Kozshplxapi.hubs.sections.item collection</summary>
        /// <param name="position">The section ID for the hubs to fetch</param>
        /// <returns>A <see cref="global::Kozshplxapi.Hubs.Sections.Item.WithSectionItemRequestBuilder"/></returns>
        public global::Kozshplxapi.Hubs.Sections.Item.WithSectionItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("sectionId", position);
                return new global::Kozshplxapi.Hubs.Sections.Item.WithSectionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Hubs.Sections.SectionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SectionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hubs/sections", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Hubs.Sections.SectionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SectionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hubs/sections", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
