// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Media.Providers.Metadata.Group;
using Kozshplxapi.Media.Providers.Metadata.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kozshplxapi.Media.Providers.Metadata
{
    /// <summary>
    /// Builds and executes requests for operations under \media\providers\metadata
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MetadataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The group property</summary>
        public global::Kozshplxapi.Media.Providers.Metadata.Group.GroupRequestBuilder Group
        {
            get => new global::Kozshplxapi.Media.Providers.Metadata.Group.GroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Kozshplxapi.media.providers.metadata.item collection</summary>
        /// <param name="position">The ID of the metadata agent provider to get</param>
        /// <returns>A <see cref="global::Kozshplxapi.Media.Providers.Metadata.Item.WithProviderItemRequestBuilder"/></returns>
        public global::Kozshplxapi.Media.Providers.Metadata.Item.WithProviderItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("providerId", position);
                return new global::Kozshplxapi.Media.Providers.Metadata.Item.WithProviderItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Media.Providers.Metadata.MetadataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MetadataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/providers/metadata?uri={uri}{&metadataTypes*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Media.Providers.Metadata.MetadataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MetadataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/providers/metadata?uri={uri}{&metadataTypes*}", rawUrl)
        {
        }
        /// <summary>
        /// Get the list of all available metadata agent providers for this PMS.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Media.Providers.Metadata.MetadataGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kozshplxapi.Media.Providers.Metadata.MetadataGetResponse?> GetAsync(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.MetadataRequestBuilder.MetadataRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kozshplxapi.Media.Providers.Metadata.MetadataGetResponse> GetAsync(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.MetadataRequestBuilder.MetadataRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kozshplxapi.Media.Providers.Metadata.MetadataGetResponse>(requestInfo, global::Kozshplxapi.Media.Providers.Metadata.MetadataGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This endpoint registers a metadata agent provider with the server. The provider URI must respond with a valid MediaProvider response.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Media.Providers.Metadata.MetadataPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kozshplxapi.Media.Providers.Metadata.MetadataPostResponse?> PostAsync(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.MetadataRequestBuilder.MetadataRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kozshplxapi.Media.Providers.Metadata.MetadataPostResponse> PostAsync(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.MetadataRequestBuilder.MetadataRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kozshplxapi.Media.Providers.Metadata.MetadataPostResponse>(requestInfo, global::Kozshplxapi.Media.Providers.Metadata.MetadataPostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the list of all available metadata agent providers for this PMS.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.MetadataRequestBuilder.MetadataRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.MetadataRequestBuilder.MetadataRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, "{+baseurl}/media/providers/metadata{?metadataTypes*}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// This endpoint registers a metadata agent provider with the server. The provider URI must respond with a valid MediaProvider response.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.MetadataRequestBuilder.MetadataRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Media.Providers.Metadata.MetadataRequestBuilder.MetadataRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/media/providers/metadata?uri={uri}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Media.Providers.Metadata.MetadataRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kozshplxapi.Media.Providers.Metadata.MetadataRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kozshplxapi.Media.Providers.Metadata.MetadataRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get the list of all available metadata agent providers for this PMS.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MetadataRequestBuilderGetQueryParameters 
        {
            /// <summary>A comma-separated list of metadata types to filter the providers by. If not specified, all providers are returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("metadataTypes")]
            public int?[]? MetadataTypes { get; set; }
#nullable restore
#else
            [QueryParameter("metadataTypes")]
            public int?[] MetadataTypes { get; set; }
#endif
        }
        /// <summary>
        /// This endpoint registers a metadata agent provider with the server. The provider URI must respond with a valid MediaProvider response.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MetadataRequestBuilderPostQueryParameters 
        {
            /// <summary>The URI of the metadata agent provider to add.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("uri")]
            public string? Uri { get; set; }
#nullable restore
#else
            [QueryParameter("uri")]
            public string Uri { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
