// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Photo.Colon.Transcode;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kozshplxapi.Photo.Colon
{
    /// <summary>
    /// Builds and executes requests for operations under \photo\:
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The transcode property</summary>
        public global::Kozshplxapi.Photo.Colon.Transcode.TranscodeRequestBuilder Transcode
        {
            get => new global::Kozshplxapi.Photo.Colon.Transcode.TranscodeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Photo.Colon.RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/photo/:", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Photo.Colon.RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/photo/:", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
