// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kozshplxapi.Media.Providers.Metadata.Group.Item.Items
{
    /// <summary>
    /// Builds and executes requests for operations under \media\providers\metadata\group\{groupId}\items
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ItemsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Kozshplxapi.media.providers.metadata.group.item.items.item collection</summary>
        /// <param name="position">The ID of the metadata agent provider</param>
        /// <returns>A <see cref="global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderItemRequestBuilder"/></returns>
        public global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("providerId", position);
                return new global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.Item.WithProviderItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.ItemsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ItemsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/providers/metadata/group/{groupId}/items", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Media.Providers.Metadata.Group.Item.Items.ItemsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ItemsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/providers/metadata/group/{groupId}/items", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
