// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Livetv.Epg.Channelmap;
using Kozshplxapi.Livetv.Epg.Channels;
using Kozshplxapi.Livetv.Epg.Countries;
using Kozshplxapi.Livetv.Epg.Languages;
using Kozshplxapi.Livetv.Epg.Lineup;
using Kozshplxapi.Livetv.Epg.Lineupchannels;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kozshplxapi.Livetv.Epg
{
    /// <summary>
    /// Builds and executes requests for operations under \livetv\epg
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EpgRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The channelmap property</summary>
        public global::Kozshplxapi.Livetv.Epg.Channelmap.ChannelmapRequestBuilder Channelmap
        {
            get => new global::Kozshplxapi.Livetv.Epg.Channelmap.ChannelmapRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The channels property</summary>
        public global::Kozshplxapi.Livetv.Epg.Channels.ChannelsRequestBuilder Channels
        {
            get => new global::Kozshplxapi.Livetv.Epg.Channels.ChannelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The countries property</summary>
        public global::Kozshplxapi.Livetv.Epg.Countries.CountriesRequestBuilder Countries
        {
            get => new global::Kozshplxapi.Livetv.Epg.Countries.CountriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The languages property</summary>
        public global::Kozshplxapi.Livetv.Epg.Languages.LanguagesRequestBuilder Languages
        {
            get => new global::Kozshplxapi.Livetv.Epg.Languages.LanguagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lineup property</summary>
        public global::Kozshplxapi.Livetv.Epg.Lineup.LineupRequestBuilder Lineup
        {
            get => new global::Kozshplxapi.Livetv.Epg.Lineup.LineupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lineupchannels property</summary>
        public global::Kozshplxapi.Livetv.Epg.Lineupchannels.LineupchannelsRequestBuilder Lineupchannels
        {
            get => new global::Kozshplxapi.Livetv.Epg.Lineupchannels.LineupchannelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Livetv.Epg.EpgRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EpgRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/livetv/epg", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Livetv.Epg.EpgRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EpgRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/livetv/epg", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
