// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Status.Sessions.History.All;
using Kozshplxapi.Status.Sessions.History.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kozshplxapi.Status.Sessions.History
{
    /// <summary>
    /// Builds and executes requests for operations under \status\sessions\history
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HistoryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::Kozshplxapi.Status.Sessions.History.All.AllRequestBuilder All
        {
            get => new global::Kozshplxapi.Status.Sessions.History.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Kozshplxapi.status.sessions.history.item collection</summary>
        /// <param name="position">The id of the history item (the `historyKey` from above)</param>
        /// <returns>A <see cref="global::Kozshplxapi.Status.Sessions.History.Item.WithHistoryItemRequestBuilder"/></returns>
        public global::Kozshplxapi.Status.Sessions.History.Item.WithHistoryItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("historyId", position);
                return new global::Kozshplxapi.Status.Sessions.History.Item.WithHistoryItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Status.Sessions.History.HistoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HistoryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/status/sessions/history", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Status.Sessions.History.HistoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HistoryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/status/sessions/history", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
