// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.DownloadQueue.Item.Add;
using Kozshplxapi.DownloadQueue.Item.Item_Escaped;
using Kozshplxapi.DownloadQueue.Item.Items;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kozshplxapi.DownloadQueue.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \downloadQueue\{queueId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithQueueItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The add property</summary>
        public global::Kozshplxapi.DownloadQueue.Item.Add.AddRequestBuilder Add
        {
            get => new global::Kozshplxapi.DownloadQueue.Item.Add.AddRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The item property</summary>
        public global::Kozshplxapi.DownloadQueue.Item.Item_Escaped.Item_EscapedRequestBuilder Item
        {
            get => new global::Kozshplxapi.DownloadQueue.Item.Item_Escaped.Item_EscapedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The items property</summary>
        public global::Kozshplxapi.DownloadQueue.Item.Items.ItemsRequestBuilder Items
        {
            get => new global::Kozshplxapi.DownloadQueue.Item.Items.ItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.DownloadQueue.Item.WithQueueItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithQueueItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/downloadQueue/{queueId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.DownloadQueue.Item.WithQueueItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithQueueItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/downloadQueue/{queueId}", rawUrl)
        {
        }
        /// <summary>
        /// Available: 0.2.0Get a download queue by its id
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.DownloadQueue.Item.WithQueueGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kozshplxapi.DownloadQueue.Item.WithQueueGetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kozshplxapi.DownloadQueue.Item.WithQueueGetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kozshplxapi.DownloadQueue.Item.WithQueueGetResponse>(requestInfo, global::Kozshplxapi.DownloadQueue.Item.WithQueueGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Available: 0.2.0Get a download queue by its id
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.DownloadQueue.Item.WithQueueItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kozshplxapi.DownloadQueue.Item.WithQueueItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kozshplxapi.DownloadQueue.Item.WithQueueItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
