// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kozshplxapi.Playlists.Item.Items.Item.Items
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ItemsGetResponse_MediaContainer_Metadata : global::Kozshplxapi.Models.Metadata, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The state of processing if this generator is part of an optimizer playlist</summary>
        public global::Kozshplxapi.Playlists.Item.Items.Item.Items.ItemsGetResponse_MediaContainer_Metadata_processingState? ProcessingState { get; set; }
        /// <summary>The error which could have occurred (or `good`)</summary>
        public global::Kozshplxapi.Playlists.Item.Items.Item.Items.ItemsGetResponse_MediaContainer_Metadata_processingStateContext? ProcessingStateContext { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Playlists.Item.Items.Item.Items.ItemsGetResponse_MediaContainer_Metadata"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Kozshplxapi.Playlists.Item.Items.Item.Items.ItemsGetResponse_MediaContainer_Metadata CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kozshplxapi.Playlists.Item.Items.Item.Items.ItemsGetResponse_MediaContainer_Metadata();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "processingState", n => { ProcessingState = n.GetEnumValue<global::Kozshplxapi.Playlists.Item.Items.Item.Items.ItemsGetResponse_MediaContainer_Metadata_processingState>(); } },
                { "processingStateContext", n => { ProcessingStateContext = n.GetEnumValue<global::Kozshplxapi.Playlists.Item.Items.Item.Items.ItemsGetResponse_MediaContainer_Metadata_processingStateContext>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteEnumValue<global::Kozshplxapi.Playlists.Item.Items.Item.Items.ItemsGetResponse_MediaContainer_Metadata_processingState>("processingState", ProcessingState);
            writer.WriteEnumValue<global::Kozshplxapi.Playlists.Item.Items.Item.Items.ItemsGetResponse_MediaContainer_Metadata_processingStateContext>("processingStateContext", ProcessingStateContext);
        }
    }
}
#pragma warning restore CS0618
