// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Playlists.Item.Items.Item.Item.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kozshplxapi.Playlists.Item.Items.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \playlists\{playlistId}\items\{generator-id}\{metadataId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithMetadataItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Kozshplxapi.playlists.item.items.item.item.item collection</summary>
        /// <param name="position">The action to perform for this item on this optimizer queue</param>
        /// <returns>A <see cref="global::Kozshplxapi.Playlists.Item.Items.Item.Item.Item.WithActionItemRequestBuilder"/></returns>
        public global::Kozshplxapi.Playlists.Item.Items.Item.Item.Item.WithActionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("action", position);
                return new global::Kozshplxapi.Playlists.Item.Items.Item.Item.Item.WithActionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Playlists.Item.Items.Item.Item.WithMetadataItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMetadataItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playlists/{playlistId}/items/{generator%2Did}/{metadataId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Playlists.Item.Items.Item.Item.WithMetadataItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMetadataItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playlists/{playlistId}/items/{generator%2Did}/{metadataId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
