// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Models;
using Kozshplxapi.Playlists.Item;
using Kozshplxapi.Playlists.Upload;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kozshplxapi.Playlists
{
    /// <summary>
    /// Builds and executes requests for operations under \playlists
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlaylistsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The upload property</summary>
        public global::Kozshplxapi.Playlists.Upload.UploadRequestBuilder Upload
        {
            get => new global::Kozshplxapi.Playlists.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Kozshplxapi.playlists.item collection</summary>
        /// <param name="position">The ID of the playlist</param>
        /// <returns>A <see cref="global::Kozshplxapi.Playlists.Item.WithPlaylistItemRequestBuilder"/></returns>
        public global::Kozshplxapi.Playlists.Item.WithPlaylistItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("playlistId", position);
                return new global::Kozshplxapi.Playlists.Item.WithPlaylistItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Playlists.PlaylistsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlaylistsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playlists{?playQueueID*,playlistType*,smart*,uri*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Playlists.PlaylistsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlaylistsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playlists{?playQueueID*,playlistType*,smart*,uri*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets a list of playlists and playlist folders for a user. General filters are permitted, such as `sort=lastViewedAt:desc`. A flat playlist list can be retrieved using `type=15` to limit the collection to just playlists.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata?> GetAsync(Action<RequestConfiguration<global::Kozshplxapi.Playlists.PlaylistsRequestBuilder.PlaylistsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata> GetAsync(Action<RequestConfiguration<global::Kozshplxapi.Playlists.PlaylistsRequestBuilder.PlaylistsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata>(requestInfo, global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new playlist. By default the playlist is blank.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata?> PostAsync(Action<RequestConfiguration<global::Kozshplxapi.Playlists.PlaylistsRequestBuilder.PlaylistsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata> PostAsync(Action<RequestConfiguration<global::Kozshplxapi.Playlists.PlaylistsRequestBuilder.PlaylistsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata>(requestInfo, global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets a list of playlists and playlist folders for a user. General filters are permitted, such as `sort=lastViewedAt:desc`. A flat playlist list can be retrieved using `type=15` to limit the collection to just playlists.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Playlists.PlaylistsRequestBuilder.PlaylistsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Playlists.PlaylistsRequestBuilder.PlaylistsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a new playlist. By default the playlist is blank.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Playlists.PlaylistsRequestBuilder.PlaylistsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Playlists.PlaylistsRequestBuilder.PlaylistsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Playlists.PlaylistsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kozshplxapi.Playlists.PlaylistsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kozshplxapi.Playlists.PlaylistsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets a list of playlists and playlist folders for a user. General filters are permitted, such as `sort=lastViewedAt:desc`. A flat playlist list can be retrieved using `type=15` to limit the collection to just playlists.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PlaylistsRequestBuilderGetQueryParameters 
        {
            /// <summary>Limit to a type of playlist</summary>
            [QueryParameter("playlistType")]
            public global::Kozshplxapi.Playlists.GetPlaylistTypeQueryParameterType? PlaylistType { get; set; }
            /// <summary>Type of playlists to return, smart or not.  When not provided, will return both.</summary>
            [QueryParameter("smart")]
            public int? Smart { get; set; }
        }
        /// <summary>
        /// Create a new playlist. By default the playlist is blank.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PlaylistsRequestBuilderPostQueryParameters 
        {
            /// <summary>To create a playlist from an existing play queue.</summary>
            [QueryParameter("playQueueID")]
            public int? PlayQueueID { get; set; }
            /// <summary>The content URI for what we&apos;re playing (e.g. `library://...`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("uri")]
            public string? Uri { get; set; }
#nullable restore
#else
            [QueryParameter("uri")]
            public string Uri { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
