// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.DownloadQueue.Item.Item_Escaped.Item.Decision;
using Kozshplxapi.DownloadQueue.Item.Item_Escaped.Item.Media;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kozshplxapi.DownloadQueue.Item.Item_Escaped.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \downloadQueue\{queueId}\item\{itemId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithItemItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The decision property</summary>
        public global::Kozshplxapi.DownloadQueue.Item.Item_Escaped.Item.Decision.DecisionRequestBuilder Decision
        {
            get => new global::Kozshplxapi.DownloadQueue.Item.Item_Escaped.Item.Decision.DecisionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The media property</summary>
        public global::Kozshplxapi.DownloadQueue.Item.Item_Escaped.Item.Media.MediaRequestBuilder Media
        {
            get => new global::Kozshplxapi.DownloadQueue.Item.Item_Escaped.Item.Media.MediaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.DownloadQueue.Item.Item_Escaped.Item.WithItemItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithItemItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/downloadQueue/{queueId}/item/{itemId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.DownloadQueue.Item.Item_Escaped.Item.WithItemItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithItemItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/downloadQueue/{queueId}/item/{itemId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
