// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kozshplxapi.Models
{
    /// <summary>They type of the value</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MediaSubscription_Setting_type
    {
        [EnumMember(Value = "bool")]
        #pragma warning disable CS1591
        Bool,
        #pragma warning restore CS1591
        [EnumMember(Value = "int")]
        #pragma warning disable CS1591
        Int,
        #pragma warning restore CS1591
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
    }
}
