// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kozshplxapi.Models
{
    /// <summary>
    /// `Media` represents an one or more media files (parts) and is a child of a metadata item. There aren&apos;t necessarily any guaranteed attributes on media elements since the attributes will vary based on the type. The possible attributes are not documented here, but they typically have self-evident names. High-level media information that can be used for badging and flagging, such as `videoResolution` and codecs, is included on the media element.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Media : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The aspectRatio property</summary>
        public double? AspectRatio { get; set; }
        /// <summary>The audioChannels property</summary>
        public int? AudioChannels { get; set; }
        /// <summary>The audioCodec property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? AudioCodec { get; set; }
#nullable restore
#else
        public UntypedNode AudioCodec { get; set; }
#endif
        /// <summary>The audioProfile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? AudioProfile { get; set; }
#nullable restore
#else
        public UntypedNode AudioProfile { get; set; }
#endif
        /// <summary>The bitrate property</summary>
        public int? Bitrate { get; set; }
        /// <summary>The container property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Container { get; set; }
#nullable restore
#else
        public UntypedNode Container { get; set; }
#endif
        /// <summary>The duration property</summary>
        public int? Duration { get; set; }
        /// <summary>The has64bitOffsets property</summary>
        public bool? Has64bitOffsets { get; set; }
        /// <summary>The hasVoiceActivity property</summary>
        public bool? HasVoiceActivity { get; set; }
        /// <summary>The height property</summary>
        public int? Height { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The optimizedForStreaming property</summary>
        public bool? OptimizedForStreaming { get; set; }
        /// <summary>The Part property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kozshplxapi.Models.Part>? Part { get; set; }
#nullable restore
#else
        public List<global::Kozshplxapi.Models.Part> Part { get; set; }
#endif
        /// <summary>The videoCodec property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? VideoCodec { get; set; }
#nullable restore
#else
        public UntypedNode VideoCodec { get; set; }
#endif
        /// <summary>The videoFrameRate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? VideoFrameRate { get; set; }
#nullable restore
#else
        public UntypedNode VideoFrameRate { get; set; }
#endif
        /// <summary>The videoProfile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? VideoProfile { get; set; }
#nullable restore
#else
        public UntypedNode VideoProfile { get; set; }
#endif
        /// <summary>The videoResolution property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? VideoResolution { get; set; }
#nullable restore
#else
        public UntypedNode VideoResolution { get; set; }
#endif
        /// <summary>The width property</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Models.Media"/> and sets the default values.
        /// </summary>
        public Media()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Models.Media"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kozshplxapi.Models.Media CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kozshplxapi.Models.Media();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aspectRatio", n => { AspectRatio = n.GetDoubleValue(); } },
                { "audioChannels", n => { AudioChannels = n.GetIntValue(); } },
                { "audioCodec", n => { AudioCodec = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "audioProfile", n => { AudioProfile = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "bitrate", n => { Bitrate = n.GetIntValue(); } },
                { "container", n => { Container = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "duration", n => { Duration = n.GetIntValue(); } },
                { "has64bitOffsets", n => { Has64bitOffsets = n.GetBoolValue(); } },
                { "hasVoiceActivity", n => { HasVoiceActivity = n.GetBoolValue(); } },
                { "height", n => { Height = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "optimizedForStreaming", n => { OptimizedForStreaming = n.GetBoolValue(); } },
                { "Part", n => { Part = n.GetCollectionOfObjectValues<global::Kozshplxapi.Models.Part>(global::Kozshplxapi.Models.Part.CreateFromDiscriminatorValue)?.AsList(); } },
                { "videoCodec", n => { VideoCodec = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "videoFrameRate", n => { VideoFrameRate = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "videoProfile", n => { VideoProfile = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "videoResolution", n => { VideoResolution = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("aspectRatio", AspectRatio);
            writer.WriteIntValue("audioChannels", AudioChannels);
            writer.WriteObjectValue<UntypedNode>("audioCodec", AudioCodec);
            writer.WriteObjectValue<UntypedNode>("audioProfile", AudioProfile);
            writer.WriteIntValue("bitrate", Bitrate);
            writer.WriteObjectValue<UntypedNode>("container", Container);
            writer.WriteIntValue("duration", Duration);
            writer.WriteBoolValue("has64bitOffsets", Has64bitOffsets);
            writer.WriteBoolValue("hasVoiceActivity", HasVoiceActivity);
            writer.WriteIntValue("height", Height);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("optimizedForStreaming", OptimizedForStreaming);
            writer.WriteCollectionOfObjectValues<global::Kozshplxapi.Models.Part>("Part", Part);
            writer.WriteObjectValue<UntypedNode>("videoCodec", VideoCodec);
            writer.WriteObjectValue<UntypedNode>("videoFrameRate", VideoFrameRate);
            writer.WriteObjectValue<UntypedNode>("videoProfile", VideoProfile);
            writer.WriteObjectValue<UntypedNode>("videoResolution", VideoResolution);
            writer.WriteIntValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
