// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kozshplxapi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MediaContainerWithPlaylistMetadata_MediaContainer_Metadata : global::Kozshplxapi.Models.Metadata, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The type of the playlist.</summary>
        public global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata_MediaContainer_Metadata_playlistType? PlaylistType { get; set; }
        /// <summary>If we return this as true then this playlist cannot be altered or deleted directly by the client.</summary>
        public bool? ReadOnly { get; set; }
        /// <summary>Whether or not the playlist is smart.</summary>
        public bool? Smart { get; set; }
        /// <summary>If this is a special playlist, this returns its type (e.g. favorites).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpecialPlaylistType { get; set; }
#nullable restore
#else
        public string SpecialPlaylistType { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata_MediaContainer_Metadata"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata_MediaContainer_Metadata CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata_MediaContainer_Metadata();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "playlistType", n => { PlaylistType = n.GetEnumValue<global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata_MediaContainer_Metadata_playlistType>(); } },
                { "readOnly", n => { ReadOnly = n.GetBoolValue(); } },
                { "smart", n => { Smart = n.GetBoolValue(); } },
                { "specialPlaylistType", n => { SpecialPlaylistType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteEnumValue<global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata_MediaContainer_Metadata_playlistType>("playlistType", PlaylistType);
            writer.WriteBoolValue("readOnly", ReadOnly);
            writer.WriteBoolValue("smart", Smart);
            writer.WriteStringValue("specialPlaylistType", SpecialPlaylistType);
        }
    }
}
#pragma warning restore CS0618
