// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kozshplxapi.Models
{
    /// <summary>The type of agent.- primary: A metadata provider which provides a unique identifier (guid) for each item.- contributor: A metadata provider which provides additional metadata for items but does not have a unique item identifier.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MetadataAgentProvider_agentType
    {
        [EnumMember(Value = "primary")]
        #pragma warning disable CS1591
        Primary,
        #pragma warning restore CS1591
        [EnumMember(Value = "contributor")]
        #pragma warning disable CS1591
        Contributor,
        #pragma warning restore CS1591
    }
}
