// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kozshplxapi.Models
{
    /// <summary>
    /// `Part` represents a particular file or &quot;part&quot; of a media item. The part is the playable unit of the media hierarchy. Suppose that a movie library contains a movie that is broken up into files, reminiscent of a movie split across two BDs. The metadata item represents information about the movie, the media item represents this instance of the movie at this resolution and quality, and the part items represent the two playable files.  If another media were added which contained the joining of these two parts transcoded down to a lower resolution, then this metadata would contain 2 medias, one with 2 parts and one with 1 part.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Part : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The audioProfile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? AudioProfile { get; set; }
#nullable restore
#else
        public UntypedNode AudioProfile { get; set; }
#endif
        /// <summary>The container of the media file, such as `mp4` or `mkv`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Container { get; set; }
#nullable restore
#else
        public UntypedNode Container { get; set; }
#endif
        /// <summary>The duration of the media item, in milliseconds</summary>
        public int? Duration { get; set; }
        /// <summary>The local file path at which the part is stored on the server</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? File { get; set; }
#nullable restore
#else
        public UntypedNode File { get; set; }
#endif
        /// <summary>The has64bitOffsets property</summary>
        public bool? Has64bitOffsets { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The key from which the media can be streamed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Key { get; set; }
#nullable restore
#else
        public UntypedNode Key { get; set; }
#endif
        /// <summary>The optimizedForStreaming property</summary>
        public bool? OptimizedForStreaming { get; set; }
        /// <summary>The size of the media, in bytes</summary>
        public long? Size { get; set; }
        /// <summary>The Stream property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kozshplxapi.Models.StreamObject>? Stream { get; set; }
#nullable restore
#else
        public List<global::Kozshplxapi.Models.StreamObject> Stream { get; set; }
#endif
        /// <summary>The videoProfile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? VideoProfile { get; set; }
#nullable restore
#else
        public UntypedNode VideoProfile { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Models.Part"/> and sets the default values.
        /// </summary>
        public Part()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Models.Part"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kozshplxapi.Models.Part CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kozshplxapi.Models.Part();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audioProfile", n => { AudioProfile = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "container", n => { Container = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "duration", n => { Duration = n.GetIntValue(); } },
                { "file", n => { File = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "has64bitOffsets", n => { Has64bitOffsets = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "key", n => { Key = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "optimizedForStreaming", n => { OptimizedForStreaming = n.GetBoolValue(); } },
                { "size", n => { Size = n.GetLongValue(); } },
                { "Stream", n => { Stream = n.GetCollectionOfObjectValues<global::Kozshplxapi.Models.StreamObject>(global::Kozshplxapi.Models.StreamObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "videoProfile", n => { VideoProfile = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("audioProfile", AudioProfile);
            writer.WriteObjectValue<UntypedNode>("container", Container);
            writer.WriteIntValue("duration", Duration);
            writer.WriteObjectValue<UntypedNode>("file", File);
            writer.WriteBoolValue("has64bitOffsets", Has64bitOffsets);
            writer.WriteIntValue("id", Id);
            writer.WriteObjectValue<UntypedNode>("key", Key);
            writer.WriteBoolValue("optimizedForStreaming", OptimizedForStreaming);
            writer.WriteLongValue("size", Size);
            writer.WriteCollectionOfObjectValues<global::Kozshplxapi.Models.StreamObject>("Stream", Stream);
            writer.WriteObjectValue<UntypedNode>("videoProfile", VideoProfile);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
