// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kozshplxapi.Models
{
    /// <summary>
    /// Each `Sort` object contains a description of the sort field.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Sort : global::Kozshplxapi.Models.DirectoryObject, IParsable
    {
        /// <summary>If present, this sort is the default and in this direction</summary>
        public global::Kozshplxapi.Models.Sort_default? Default { get; set; }
        /// <summary>This default diction of this sort</summary>
        public global::Kozshplxapi.Models.Sort_defaultDirection? DefaultDirection { get; set; }
        /// <summary>The key for sorting this field in reverse order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DescKey { get; set; }
#nullable restore
#else
        public string DescKey { get; set; }
#endif
        /// <summary>The key to use to get items sorted by this field and indexed by the first character</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstCharacterKey { get; set; }
#nullable restore
#else
        public string FirstCharacterKey { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Models.Sort"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Kozshplxapi.Models.Sort CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kozshplxapi.Models.Sort();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "default", n => { Default = n.GetEnumValue<global::Kozshplxapi.Models.Sort_default>(); } },
                { "defaultDirection", n => { DefaultDirection = n.GetEnumValue<global::Kozshplxapi.Models.Sort_defaultDirection>(); } },
                { "descKey", n => { DescKey = n.GetStringValue(); } },
                { "firstCharacterKey", n => { FirstCharacterKey = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteEnumValue<global::Kozshplxapi.Models.Sort_default>("default", Default);
            writer.WriteEnumValue<global::Kozshplxapi.Models.Sort_defaultDirection>("defaultDirection", DefaultDirection);
            writer.WriteStringValue("descKey", DescKey);
            writer.WriteStringValue("firstCharacterKey", FirstCharacterKey);
        }
    }
}
#pragma warning restore CS0618
