// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kozshplxapi.Models
{
    /// <summary>
    /// `Stream` represents a particular stream from a media item, such as the video stream, audio stream, or subtitle stream. The stream may either be part of the file represented by the parent `Part` or, especially for subtitles, an external file. The stream contains more detailed information about the specific stream. For example, a video may include the `aspectRatio` at the `Media` level, but detailed information about the video stream like the color space will be included on the `Stream` for the video stream.  Note that photos do not have streams (mostly as an optimization).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StreamObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The audioChannelLayout property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? AudioChannelLayout { get; set; }
#nullable restore
#else
        public UntypedNode AudioChannelLayout { get; set; }
#endif
        /// <summary>The bitDepth property</summary>
        public int? BitDepth { get; set; }
        /// <summary>The bitrate property</summary>
        public int? Bitrate { get; set; }
        /// <summary>For subtitle streams only. If `true` then the server can attempt to automatically sync the subtitle timestamps with the video.</summary>
        public bool? CanAutoSync { get; set; }
        /// <summary>The chromaLocation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ChromaLocation { get; set; }
#nullable restore
#else
        public UntypedNode ChromaLocation { get; set; }
#endif
        /// <summary>The chromaSubsampling property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ChromaSubsampling { get; set; }
#nullable restore
#else
        public UntypedNode ChromaSubsampling { get; set; }
#endif
        /// <summary>The codec of the stream, such as `h264` or `aac`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Codec { get; set; }
#nullable restore
#else
        public UntypedNode Codec { get; set; }
#endif
        /// <summary>The colorPrimaries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ColorPrimaries { get; set; }
#nullable restore
#else
        public UntypedNode ColorPrimaries { get; set; }
#endif
        /// <summary>The colorRange property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ColorRange { get; set; }
#nullable restore
#else
        public UntypedNode ColorRange { get; set; }
#endif
        /// <summary>The colorSpace property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ColorSpace { get; set; }
#nullable restore
#else
        public UntypedNode ColorSpace { get; set; }
#endif
        /// <summary>The colorTrc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ColorTrc { get; set; }
#nullable restore
#else
        public UntypedNode ColorTrc { get; set; }
#endif
        /// <summary>The default property</summary>
        public bool? Default { get; set; }
        /// <summary>A friendly name for the stream, often comprised of the language and codec information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DisplayTitle { get; set; }
#nullable restore
#else
        public UntypedNode DisplayTitle { get; set; }
#endif
        /// <summary>The frameRate property</summary>
        public double? FrameRate { get; set; }
        /// <summary>The hasScalingMatrix property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? HasScalingMatrix { get; set; }
#nullable restore
#else
        public UntypedNode HasScalingMatrix { get; set; }
#endif
        /// <summary>The height property</summary>
        public int? Height { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>If the stream is part of the `Part` and not an external resource, the index of the stream within that part</summary>
        public int? Index { get; set; }
        /// <summary>If the stream is independently streamable, the key from which it can be streamed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Key { get; set; }
#nullable restore
#else
        public UntypedNode Key { get; set; }
#endif
        /// <summary>The language property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Language { get; set; }
#nullable restore
#else
        public UntypedNode Language { get; set; }
#endif
        /// <summary>The three character language code for the stream contents</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? LanguageCode { get; set; }
#nullable restore
#else
        public UntypedNode LanguageCode { get; set; }
#endif
        /// <summary>The level property</summary>
        public int? Level { get; set; }
        /// <summary>The profile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Profile { get; set; }
#nullable restore
#else
        public UntypedNode Profile { get; set; }
#endif
        /// <summary>The refFrames property</summary>
        public int? RefFrames { get; set; }
        /// <summary>The samplingRate property</summary>
        public int? SamplingRate { get; set; }
        /// <summary>The selected property</summary>
        public bool? Selected { get; set; }
        /// <summary>The streamIdentifier property</summary>
        public int? StreamIdentifier { get; set; }
        /// <summary>A number indicating the type of the stream. `1` for video, `2` for audio, `3` for subtitles, `4` for lyrics</summary>
        public int? StreamType { get; set; }
        /// <summary>The width property</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Models.StreamObject"/> and sets the default values.
        /// </summary>
        public StreamObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Models.StreamObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kozshplxapi.Models.StreamObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kozshplxapi.Models.StreamObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audioChannelLayout", n => { AudioChannelLayout = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "bitDepth", n => { BitDepth = n.GetIntValue(); } },
                { "bitrate", n => { Bitrate = n.GetIntValue(); } },
                { "canAutoSync", n => { CanAutoSync = n.GetBoolValue(); } },
                { "chromaLocation", n => { ChromaLocation = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "chromaSubsampling", n => { ChromaSubsampling = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "codec", n => { Codec = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "colorPrimaries", n => { ColorPrimaries = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "colorRange", n => { ColorRange = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "colorSpace", n => { ColorSpace = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "colorTrc", n => { ColorTrc = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "default", n => { Default = n.GetBoolValue(); } },
                { "displayTitle", n => { DisplayTitle = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "frameRate", n => { FrameRate = n.GetDoubleValue(); } },
                { "hasScalingMatrix", n => { HasScalingMatrix = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "height", n => { Height = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "index", n => { Index = n.GetIntValue(); } },
                { "key", n => { Key = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "language", n => { Language = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "languageCode", n => { LanguageCode = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "level", n => { Level = n.GetIntValue(); } },
                { "profile", n => { Profile = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "refFrames", n => { RefFrames = n.GetIntValue(); } },
                { "samplingRate", n => { SamplingRate = n.GetIntValue(); } },
                { "selected", n => { Selected = n.GetBoolValue(); } },
                { "streamIdentifier", n => { StreamIdentifier = n.GetIntValue(); } },
                { "streamType", n => { StreamType = n.GetIntValue(); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("audioChannelLayout", AudioChannelLayout);
            writer.WriteIntValue("bitDepth", BitDepth);
            writer.WriteIntValue("bitrate", Bitrate);
            writer.WriteBoolValue("canAutoSync", CanAutoSync);
            writer.WriteObjectValue<UntypedNode>("chromaLocation", ChromaLocation);
            writer.WriteObjectValue<UntypedNode>("chromaSubsampling", ChromaSubsampling);
            writer.WriteObjectValue<UntypedNode>("codec", Codec);
            writer.WriteObjectValue<UntypedNode>("colorPrimaries", ColorPrimaries);
            writer.WriteObjectValue<UntypedNode>("colorRange", ColorRange);
            writer.WriteObjectValue<UntypedNode>("colorSpace", ColorSpace);
            writer.WriteObjectValue<UntypedNode>("colorTrc", ColorTrc);
            writer.WriteBoolValue("default", Default);
            writer.WriteObjectValue<UntypedNode>("displayTitle", DisplayTitle);
            writer.WriteDoubleValue("frameRate", FrameRate);
            writer.WriteObjectValue<UntypedNode>("hasScalingMatrix", HasScalingMatrix);
            writer.WriteIntValue("height", Height);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("index", Index);
            writer.WriteObjectValue<UntypedNode>("key", Key);
            writer.WriteObjectValue<UntypedNode>("language", Language);
            writer.WriteObjectValue<UntypedNode>("languageCode", LanguageCode);
            writer.WriteIntValue("level", Level);
            writer.WriteObjectValue<UntypedNode>("profile", Profile);
            writer.WriteIntValue("refFrames", RefFrames);
            writer.WriteIntValue("samplingRate", SamplingRate);
            writer.WriteBoolValue("selected", Selected);
            writer.WriteIntValue("streamIdentifier", StreamIdentifier);
            writer.WriteIntValue("streamType", StreamType);
            writer.WriteIntValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
