// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kozshplxapi.Models
{
    /// <summary>
    /// A variety of extra information about a metadata item is included as tags. These tags use their own element names such as `Genre`, `Writer`, `Directory`, and `Role`. Individual tag types may introduce their own extra attributes.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Tag : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Measure of the confidence of an automatic tag</summary>
        public double? Confidence { get; set; }
        /// <summary>The context property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Context { get; set; }
#nullable restore
#else
        public string Context { get; set; }
#endif
        /// <summary>A filter parameter that can be used to query for more content that matches this tag value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Filter { get; set; }
#nullable restore
#else
        public UntypedNode Filter { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The ratingKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RatingKey { get; set; }
#nullable restore
#else
        public string RatingKey { get; set; }
#endif
        /// <summary>The role this actor played</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Role { get; set; }
#nullable restore
#else
        public UntypedNode Role { get; set; }
#endif
        /// <summary>Plex identifier for this tag which can be used to fetch additional information from plex.tv</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? TagKey { get; set; }
#nullable restore
#else
        public UntypedNode TagKey { get; set; }
#endif
        /// <summary>The value of the tag (the name)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? TagProp { get; set; }
#nullable restore
#else
        public UntypedNode TagProp { get; set; }
#endif
        /// <summary>The tagType property</summary>
        public int? TagType { get; set; }
        /// <summary>The thumb property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Thumb { get; set; }
#nullable restore
#else
        public UntypedNode Thumb { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Models.Tag"/> and sets the default values.
        /// </summary>
        public Tag()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Models.Tag"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kozshplxapi.Models.Tag CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kozshplxapi.Models.Tag();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "confidence", n => { Confidence = n.GetDoubleValue(); } },
                { "context", n => { Context = n.GetStringValue(); } },
                { "filter", n => { Filter = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "ratingKey", n => { RatingKey = n.GetStringValue(); } },
                { "role", n => { Role = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "tagKey", n => { TagKey = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "tag", n => { TagProp = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "tagType", n => { TagType = n.GetIntValue(); } },
                { "thumb", n => { Thumb = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("confidence", Confidence);
            writer.WriteStringValue("context", Context);
            writer.WriteObjectValue<UntypedNode>("filter", Filter);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("ratingKey", RatingKey);
            writer.WriteObjectValue<UntypedNode>("role", Role);
            writer.WriteObjectValue<UntypedNode>("tagKey", TagKey);
            writer.WriteObjectValue<UntypedNode>("tag", TagProp);
            writer.WriteIntValue("tagType", TagType);
            writer.WriteObjectValue<UntypedNode>("thumb", Thumb);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
