// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kozshplxapi.Playlists.Item.Items.Item.Move
{
    /// <summary>
    /// Builds and executes requests for operations under \playlists\{playlistId}\items\{generator-id}\move
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MoveRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Playlists.Item.Items.Item.Move.MoveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MoveRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playlists/{playlistId}/items/{generator%2Did}/move{?after*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Playlists.Item.Items.Item.Move.MoveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MoveRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playlists/{playlistId}/items/{generator%2Did}/move{?after*}", rawUrl)
        {
        }
        /// <summary>
        /// Moves an item in a playlist. Only works with dumb playlists.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata?> PutAsync(Action<RequestConfiguration<global::Kozshplxapi.Playlists.Item.Items.Item.Move.MoveRequestBuilder.MoveRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata> PutAsync(Action<RequestConfiguration<global::Kozshplxapi.Playlists.Item.Items.Item.Move.MoveRequestBuilder.MoveRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPutRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata>(requestInfo, global::Kozshplxapi.Models.MediaContainerWithPlaylistMetadata.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Moves an item in a playlist. Only works with dumb playlists.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Playlists.Item.Items.Item.Move.MoveRequestBuilder.MoveRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Playlists.Item.Items.Item.Move.MoveRequestBuilder.MoveRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Playlists.Item.Items.Item.Move.MoveRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kozshplxapi.Playlists.Item.Items.Item.Move.MoveRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kozshplxapi.Playlists.Item.Items.Item.Move.MoveRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Moves an item in a playlist. Only works with dumb playlists.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MoveRequestBuilderPutQueryParameters 
        {
            /// <summary>The playlist item ID to insert the new item after.  If not provided, item is moved to beginning of playlist</summary>
            [QueryParameter("after")]
            public int? After { get; set; }
        }
    }
}
#pragma warning restore CS0618
