// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Hubs.ContinueWatching;
using Kozshplxapi.Hubs.Items;
using Kozshplxapi.Hubs.Metadata;
using Kozshplxapi.Hubs.Promoted;
using Kozshplxapi.Hubs.Search;
using Kozshplxapi.Hubs.Sections;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kozshplxapi.Hubs
{
    /// <summary>
    /// Builds and executes requests for operations under \hubs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HubsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The continueWatching property</summary>
        public global::Kozshplxapi.Hubs.ContinueWatching.ContinueWatchingRequestBuilder ContinueWatching
        {
            get => new global::Kozshplxapi.Hubs.ContinueWatching.ContinueWatchingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The items property</summary>
        public global::Kozshplxapi.Hubs.Items.ItemsRequestBuilder Items
        {
            get => new global::Kozshplxapi.Hubs.Items.ItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metadata property</summary>
        public global::Kozshplxapi.Hubs.Metadata.MetadataRequestBuilder Metadata
        {
            get => new global::Kozshplxapi.Hubs.Metadata.MetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The promoted property</summary>
        public global::Kozshplxapi.Hubs.Promoted.PromotedRequestBuilder Promoted
        {
            get => new global::Kozshplxapi.Hubs.Promoted.PromotedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Kozshplxapi.Hubs.Search.SearchRequestBuilder Search
        {
            get => new global::Kozshplxapi.Hubs.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sections property</summary>
        public global::Kozshplxapi.Hubs.Sections.SectionsRequestBuilder Sections
        {
            get => new global::Kozshplxapi.Hubs.Sections.SectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Hubs.HubsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HubsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hubs{?count*,identifier*,onlyTransient*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Hubs.HubsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HubsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hubs{?count*,identifier*,onlyTransient*}", rawUrl)
        {
        }
        /// <summary>
        /// Get the global hubs in this PMS
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Hubs.HubsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kozshplxapi.Hubs.HubsGetResponse?> GetAsync(Action<RequestConfiguration<global::Kozshplxapi.Hubs.HubsRequestBuilder.HubsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kozshplxapi.Hubs.HubsGetResponse> GetAsync(Action<RequestConfiguration<global::Kozshplxapi.Hubs.HubsRequestBuilder.HubsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kozshplxapi.Hubs.HubsGetResponse>(requestInfo, global::Kozshplxapi.Hubs.HubsGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the global hubs in this PMS
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Hubs.HubsRequestBuilder.HubsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kozshplxapi.Hubs.HubsRequestBuilder.HubsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kozshplxapi.Hubs.HubsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kozshplxapi.Hubs.HubsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kozshplxapi.Hubs.HubsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get the global hubs in this PMS
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class HubsRequestBuilderGetQueryParameters 
        {
            /// <summary>Limit hub entries to count items</summary>
            [QueryParameter("count")]
            public int? Count { get; set; }
            /// <summary>If provided, limit to only specified hubs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("identifier")]
            public string[]? Identifier { get; set; }
#nullable restore
#else
            [QueryParameter("identifier")]
            public string[] Identifier { get; set; }
#endif
            /// <summary>Only return hubs which are &quot;transient&quot;, meaning those which are prone to changing after media playback or addition (e.g. On Deck, or Recently Added)</summary>
            [QueryParameter("onlyTransient")]
            public int? OnlyTransient { get; set; }
        }
    }
}
#pragma warning restore CS0618
