// <auto-generated/>
#pragma warning disable CS0618
using Kozshplxapi.Colon.Websocket.Notifications;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kozshplxapi.Colon.Websocket
{
    /// <summary>
    /// Builds and executes requests for operations under \:\websocket
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebsocketRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The notifications property</summary>
        public global::Kozshplxapi.Colon.Websocket.Notifications.NotificationsRequestBuilder Notifications
        {
            get => new global::Kozshplxapi.Colon.Websocket.Notifications.NotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Colon.Websocket.WebsocketRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebsocketRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/:/websocket", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kozshplxapi.Colon.Websocket.WebsocketRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebsocketRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/:/websocket", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
